name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main  # 触发工作流的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 选择Python版本

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -U jupyter-book

    - name: Build the book
      run: jupyter-book build .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
